// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.remo.user;

public interface GetUserInfoResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.remo.user.GetUserInfoResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 userId = 1;</code>
     */
    int getUserId();

    /**
     * <code>optional string userName = 2;</code>
     */
    String getUserName();

    /**
     * <code>optional string userName = 2;</code>
     */
    com.google.protobuf.ByteString
    getUserNameBytes();

    /**
     * <code>optional string phone = 3;</code>
     */
    String getPhone();

    /**
     * <code>optional string phone = 3;</code>
     */
    com.google.protobuf.ByteString
    getPhoneBytes();
}
