// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.remo.user;

public interface GetUserInfoRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.remo.user.GetUserInfoRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 userId = 1;</code>
     */
    int getUserId();
}
