// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.remo.user;

/**
 * <pre>
 * 定义消息（响应）
 * </pre>
 * <p>
 * Protobuf type {@code org.remo.user.GetUserInfoResponse}
 */
public final class GetUserInfoResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:org.remo.user.GetUserInfoResponse)
        GetUserInfoResponseOrBuilder {
    public static final int USERID_FIELD_NUMBER = 1;
    public static final int USERNAME_FIELD_NUMBER = 2;
    public static final int PHONE_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:org.remo.user.GetUserInfoResponse)
    private static final GetUserInfoResponse DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<GetUserInfoResponse>
            PARSER = new com.google.protobuf.AbstractParser<GetUserInfoResponse>() {
        public GetUserInfoResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new GetUserInfoResponse(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new GetUserInfoResponse();
    }

    private int userId_;
    private volatile Object userName_;
    private volatile Object phone_;
    private byte memoizedIsInitialized = -1;

    // Use GetUserInfoResponse.newBuilder() to construct.
    private GetUserInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private GetUserInfoResponse() {
        userId_ = 0;
        userName_ = "";
        phone_ = "";
    }

    private GetUserInfoResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        userId_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        userName_ = s;
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        phone_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return RPCUserServiceApi.internal_static_org_remo_user_GetUserInfoResponse_descriptor;
    }

    public static GetUserInfoResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GetUserInfoResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GetUserInfoResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GetUserInfoResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GetUserInfoResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static GetUserInfoResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static GetUserInfoResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static GetUserInfoResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static GetUserInfoResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static GetUserInfoResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(GetUserInfoResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static GetUserInfoResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<GetUserInfoResponse> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return RPCUserServiceApi.internal_static_org_remo_user_GetUserInfoResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        GetUserInfoResponse.class, Builder.class);
    }

    /**
     * <code>optional int32 userId = 1;</code>
     */
    public int getUserId() {
        return userId_;
    }

    /**
     * <code>optional string userName = 2;</code>
     */
    public String getUserName() {
        Object ref = userName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            userName_ = s;
            return s;
        }
    }

    /**
     * <code>optional string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
    getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            userName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>optional string phone = 3;</code>
     */
    public String getPhone() {
        Object ref = phone_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            phone_ = s;
            return s;
        }
    }

    /**
     * <code>optional string phone = 3;</code>
     */
    public com.google.protobuf.ByteString
    getPhoneBytes() {
        Object ref = phone_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            phone_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (userId_ != 0) {
            output.writeInt32(1, userId_);
        }
        if (!getUserNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
        }
        if (!getPhoneBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phone_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (userId_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, userId_);
        }
        if (!getUserNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
        }
        if (!getPhoneBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phone_);
        }
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof GetUserInfoResponse)) {
            return super.equals(obj);
        }
        GetUserInfoResponse other = (GetUserInfoResponse) obj;

        boolean result = true;
        result = result && (getUserId()
                == other.getUserId());
        result = result && getUserName()
                .equals(other.getUserName());
        result = result && getPhone()
                .equals(other.getPhone());
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId();
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserName().hashCode();
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhone().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<GetUserInfoResponse> getParserForType() {
        return PARSER;
    }

    public GetUserInfoResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * 定义消息（响应）
     * </pre>
     * <p>
     * Protobuf type {@code org.remo.user.GetUserInfoResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:org.remo.user.GetUserInfoResponse)
            GetUserInfoResponseOrBuilder {
        private int userId_;
        private Object userName_ = "";
        private Object phone_ = "";

        // Construct using org.remo.user.GetUserInfoResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return RPCUserServiceApi.internal_static_org_remo_user_GetUserInfoResponse_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return RPCUserServiceApi.internal_static_org_remo_user_GetUserInfoResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            GetUserInfoResponse.class, Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            userId_ = 0;

            userName_ = "";

            phone_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return RPCUserServiceApi.internal_static_org_remo_user_GetUserInfoResponse_descriptor;
        }

        public GetUserInfoResponse getDefaultInstanceForType() {
            return GetUserInfoResponse.getDefaultInstance();
        }

        public GetUserInfoResponse build() {
            GetUserInfoResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public GetUserInfoResponse buildPartial() {
            GetUserInfoResponse result = new GetUserInfoResponse(this);
            result.userId_ = userId_;
            result.userName_ = userName_;
            result.phone_ = phone_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof GetUserInfoResponse) {
                return mergeFrom((GetUserInfoResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(GetUserInfoResponse other) {
            if (other == GetUserInfoResponse.getDefaultInstance()) return this;
            if (other.getUserId() != 0) {
                setUserId(other.getUserId());
            }
            if (!other.getUserName().isEmpty()) {
                userName_ = other.userName_;
                onChanged();
            }
            if (!other.getPhone().isEmpty()) {
                phone_ = other.phone_;
                onChanged();
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            GetUserInfoResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (GetUserInfoResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>optional int32 userId = 1;</code>
         */
        public int getUserId() {
            return userId_;
        }

        /**
         * <code>optional int32 userId = 1;</code>
         */
        public Builder setUserId(int value) {

            userId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional int32 userId = 1;</code>
         */
        public Builder clearUserId() {

            userId_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>optional string userName = 2;</code>
         */
        public String getUserName() {
            Object ref = userName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                userName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>optional string userName = 2;</code>
         */
        public Builder setUserName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            userName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional string userName = 2;</code>
         */
        public com.google.protobuf.ByteString
        getUserNameBytes() {
            Object ref = userName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                userName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string userName = 2;</code>
         */
        public Builder setUserNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            userName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional string userName = 2;</code>
         */
        public Builder clearUserName() {

            userName_ = getDefaultInstance().getUserName();
            onChanged();
            return this;
        }

        /**
         * <code>optional string phone = 3;</code>
         */
        public String getPhone() {
            Object ref = phone_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                phone_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>optional string phone = 3;</code>
         */
        public Builder setPhone(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            phone_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional string phone = 3;</code>
         */
        public com.google.protobuf.ByteString
        getPhoneBytes() {
            Object ref = phone_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                phone_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string phone = 3;</code>
         */
        public Builder setPhoneBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            phone_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional string phone = 3;</code>
         */
        public Builder clearPhone() {

            phone_ = getDefaultInstance().getPhone();
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:org.remo.user.GetUserInfoResponse)
    }

}

