// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.remo.user;

public interface ListUserInfoResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.remo.user.ListUserInfoResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
     */
    java.util.List<GetUserInfoResponse>
    getUsersList();

    /**
     * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
     */
    GetUserInfoResponse getUsers(int index);

    /**
     * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
     */
    int getUsersCount();

    /**
     * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
     */
    java.util.List<? extends GetUserInfoResponseOrBuilder>
    getUsersOrBuilderList();

    /**
     * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
     */
    GetUserInfoResponseOrBuilder getUsersOrBuilder(
            int index);
}
