// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.remo.user;

/**
 * <pre>
 * 定义消息（响应）
 * </pre>
 * <p>
 * Protobuf type {@code org.remo.user.ListUserInfoResponse}
 */
public final class ListUserInfoResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:org.remo.user.ListUserInfoResponse)
        ListUserInfoResponseOrBuilder {
    public static final int USERS_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:org.remo.user.ListUserInfoResponse)
    private static final ListUserInfoResponse DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<ListUserInfoResponse>
            PARSER = new com.google.protobuf.AbstractParser<ListUserInfoResponse>() {
        public ListUserInfoResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new ListUserInfoResponse(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new ListUserInfoResponse();
    }

    private java.util.List<GetUserInfoResponse> users_;
    private byte memoizedIsInitialized = -1;

    // Use ListUserInfoResponse.newBuilder() to construct.
    private ListUserInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ListUserInfoResponse() {
        users_ = java.util.Collections.emptyList();
    }

    private ListUserInfoResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            users_ = new java.util.ArrayList<GetUserInfoResponse>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        users_.add(
                                input.readMessage(GetUserInfoResponse.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                users_ = java.util.Collections.unmodifiableList(users_);
            }
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return RPCUserServiceApi.internal_static_org_remo_user_ListUserInfoResponse_descriptor;
    }

    public static ListUserInfoResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ListUserInfoResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ListUserInfoResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ListUserInfoResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ListUserInfoResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static ListUserInfoResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ListUserInfoResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static ListUserInfoResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ListUserInfoResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static ListUserInfoResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ListUserInfoResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static ListUserInfoResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<ListUserInfoResponse> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return RPCUserServiceApi.internal_static_org_remo_user_ListUserInfoResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        ListUserInfoResponse.class, Builder.class);
    }

    /**
     * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
     */
    public java.util.List<GetUserInfoResponse> getUsersList() {
        return users_;
    }

    /**
     * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
     */
    public java.util.List<? extends GetUserInfoResponseOrBuilder>
    getUsersOrBuilderList() {
        return users_;
    }

    /**
     * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
     */
    public int getUsersCount() {
        return users_.size();
    }

    /**
     * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
     */
    public GetUserInfoResponse getUsers(int index) {
        return users_.get(index);
    }

    /**
     * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
     */
    public GetUserInfoResponseOrBuilder getUsersOrBuilder(
            int index) {
        return users_.get(index);
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        for (int i = 0; i < users_.size(); i++) {
            output.writeMessage(1, users_.get(i));
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < users_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, users_.get(i));
        }
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof ListUserInfoResponse)) {
            return super.equals(obj);
        }
        ListUserInfoResponse other = (ListUserInfoResponse) obj;

        boolean result = true;
        result = result && getUsersList()
                .equals(other.getUsersList());
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (getUsersCount() > 0) {
            hash = (37 * hash) + USERS_FIELD_NUMBER;
            hash = (53 * hash) + getUsersList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<ListUserInfoResponse> getParserForType() {
        return PARSER;
    }

    public ListUserInfoResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * 定义消息（响应）
     * </pre>
     * <p>
     * Protobuf type {@code org.remo.user.ListUserInfoResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:org.remo.user.ListUserInfoResponse)
            ListUserInfoResponseOrBuilder {
        private int bitField0_;
        private java.util.List<GetUserInfoResponse> users_ =
                java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
                GetUserInfoResponse, GetUserInfoResponse.Builder, GetUserInfoResponseOrBuilder> usersBuilder_;

        // Construct using org.remo.user.ListUserInfoResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return RPCUserServiceApi.internal_static_org_remo_user_ListUserInfoResponse_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return RPCUserServiceApi.internal_static_org_remo_user_ListUserInfoResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ListUserInfoResponse.class, Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getUsersFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            if (usersBuilder_ == null) {
                users_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                usersBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return RPCUserServiceApi.internal_static_org_remo_user_ListUserInfoResponse_descriptor;
        }

        public ListUserInfoResponse getDefaultInstanceForType() {
            return ListUserInfoResponse.getDefaultInstance();
        }

        public ListUserInfoResponse build() {
            ListUserInfoResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public ListUserInfoResponse buildPartial() {
            ListUserInfoResponse result = new ListUserInfoResponse(this);
            int from_bitField0_ = bitField0_;
            if (usersBuilder_ == null) {
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    users_ = java.util.Collections.unmodifiableList(users_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.users_ = users_;
            } else {
                result.users_ = usersBuilder_.build();
            }
            onBuilt();
            return result;
        }

        public Builder clone() {
            return super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof ListUserInfoResponse) {
                return mergeFrom((ListUserInfoResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(ListUserInfoResponse other) {
            if (other == ListUserInfoResponse.getDefaultInstance()) return this;
            if (usersBuilder_ == null) {
                if (!other.users_.isEmpty()) {
                    if (users_.isEmpty()) {
                        users_ = other.users_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureUsersIsMutable();
                        users_.addAll(other.users_);
                    }
                    onChanged();
                }
            } else {
                if (!other.users_.isEmpty()) {
                    if (usersBuilder_.isEmpty()) {
                        usersBuilder_.dispose();
                        usersBuilder_ = null;
                        users_ = other.users_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        usersBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getUsersFieldBuilder() : null;
                    } else {
                        usersBuilder_.addAllMessages(other.users_);
                    }
                }
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            ListUserInfoResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (ListUserInfoResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensureUsersIsMutable() {
            if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                users_ = new java.util.ArrayList<GetUserInfoResponse>(users_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public java.util.List<GetUserInfoResponse> getUsersList() {
            if (usersBuilder_ == null) {
                return java.util.Collections.unmodifiableList(users_);
            } else {
                return usersBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public int getUsersCount() {
            if (usersBuilder_ == null) {
                return users_.size();
            } else {
                return usersBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public GetUserInfoResponse getUsers(int index) {
            if (usersBuilder_ == null) {
                return users_.get(index);
            } else {
                return usersBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public Builder setUsers(
                int index, GetUserInfoResponse value) {
            if (usersBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUsersIsMutable();
                users_.set(index, value);
                onChanged();
            } else {
                usersBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public Builder setUsers(
                int index, GetUserInfoResponse.Builder builderForValue) {
            if (usersBuilder_ == null) {
                ensureUsersIsMutable();
                users_.set(index, builderForValue.build());
                onChanged();
            } else {
                usersBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public Builder addUsers(GetUserInfoResponse value) {
            if (usersBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUsersIsMutable();
                users_.add(value);
                onChanged();
            } else {
                usersBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public Builder addUsers(
                int index, GetUserInfoResponse value) {
            if (usersBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUsersIsMutable();
                users_.add(index, value);
                onChanged();
            } else {
                usersBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public Builder addUsers(
                GetUserInfoResponse.Builder builderForValue) {
            if (usersBuilder_ == null) {
                ensureUsersIsMutable();
                users_.add(builderForValue.build());
                onChanged();
            } else {
                usersBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public Builder addUsers(
                int index, GetUserInfoResponse.Builder builderForValue) {
            if (usersBuilder_ == null) {
                ensureUsersIsMutable();
                users_.add(index, builderForValue.build());
                onChanged();
            } else {
                usersBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public Builder addAllUsers(
                Iterable<? extends GetUserInfoResponse> values) {
            if (usersBuilder_ == null) {
                ensureUsersIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, users_);
                onChanged();
            } else {
                usersBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public Builder clearUsers() {
            if (usersBuilder_ == null) {
                users_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                usersBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public Builder removeUsers(int index) {
            if (usersBuilder_ == null) {
                ensureUsersIsMutable();
                users_.remove(index);
                onChanged();
            } else {
                usersBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public GetUserInfoResponse.Builder getUsersBuilder(
                int index) {
            return getUsersFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public GetUserInfoResponseOrBuilder getUsersOrBuilder(
                int index) {
            if (usersBuilder_ == null) {
                return users_.get(index);
            } else {
                return usersBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public java.util.List<? extends GetUserInfoResponseOrBuilder>
        getUsersOrBuilderList() {
            if (usersBuilder_ != null) {
                return usersBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(users_);
            }
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public GetUserInfoResponse.Builder addUsersBuilder() {
            return getUsersFieldBuilder().addBuilder(
                    GetUserInfoResponse.getDefaultInstance());
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public GetUserInfoResponse.Builder addUsersBuilder(
                int index) {
            return getUsersFieldBuilder().addBuilder(
                    index, GetUserInfoResponse.getDefaultInstance());
        }

        /**
         * <code>repeated .org.remo.user.GetUserInfoResponse users = 1;</code>
         */
        public java.util.List<GetUserInfoResponse.Builder>
        getUsersBuilderList() {
            return getUsersFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                GetUserInfoResponse, GetUserInfoResponse.Builder, GetUserInfoResponseOrBuilder>
        getUsersFieldBuilder() {
            if (usersBuilder_ == null) {
                usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        GetUserInfoResponse, GetUserInfoResponse.Builder, GetUserInfoResponseOrBuilder>(
                        users_,
                        ((bitField0_ & 0x00000001) == 0x00000001),
                        getParentForChildren(),
                        isClean());
                users_ = null;
            }
            return usersBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:org.remo.user.ListUserInfoResponse)
    }

}

