// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.remo.user;

public interface ListUserInfoRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.remo.user.ListUserInfoRequest)
        com.google.protobuf.MessageOrBuilder {
}
