// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.remo.user;

public final class RPCUserServiceApi {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_remo_user_ListUserInfoRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_org_remo_user_ListUserInfoRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_remo_user_GetUserInfoRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_org_remo_user_GetUserInfoRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_remo_user_GetUserInfoResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_org_remo_user_GetUserInfoResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_remo_user_ListUserInfoResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_org_remo_user_ListUserInfoResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\nuser.proto\022\rorg.remo.user\"\025\n\023ListUserI" +
                        "nfoRequest\"$\n\022GetUserInfoRequest\022\016\n\006user" +
                        "Id\030\001 \001(\005\"F\n\023GetUserInfoResponse\022\016\n\006userI" +
                        "d\030\001 \001(\005\022\020\n\010userName\030\002 \001(\t\022\r\n\005phone\030\003 \001(\t" +
                        "\"I\n\024ListUserInfoResponse\0221\n\005users\030\001 \003(\0132" +
                        "\".org.remo.user.GetUserInfoResponse2\273\001\n\016" +
                        "RPCUserService\022R\n\007getUser\022!.org.remo.use" +
                        "r.GetUserInfoRequest\032\".org.remo.user.Get" +
                        "UserInfoResponse\"\000\022U\n\010listUser\022\".org.rem" +
                        "o.user.ListUserInfoRequest\032#.org.remo.us",
                "er.ListUserInfoResponse\"\000B$\n\rorg.remo.us" +
                        "erB\021RPCUserServiceApiP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_org_remo_user_ListUserInfoRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_org_remo_user_ListUserInfoRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_org_remo_user_ListUserInfoRequest_descriptor,
                new String[]{});
        internal_static_org_remo_user_GetUserInfoRequest_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_org_remo_user_GetUserInfoRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_org_remo_user_GetUserInfoRequest_descriptor,
                new String[]{"UserId",});
        internal_static_org_remo_user_GetUserInfoResponse_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_org_remo_user_GetUserInfoResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_org_remo_user_GetUserInfoResponse_descriptor,
                new String[]{"UserId", "UserName", "Phone",});
        internal_static_org_remo_user_ListUserInfoResponse_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_org_remo_user_ListUserInfoResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_org_remo_user_ListUserInfoResponse_descriptor,
                new String[]{"Users",});
    }

    private RPCUserServiceApi() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
