// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package org.remo.api;

public interface RPCDateResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.remo.api.RPCDateResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serverDate = 1;</code>
     */
    String getServerDate();

    /**
     * <code>optional string serverDate = 1;</code>
     */
    com.google.protobuf.ByteString
    getServerDateBytes();
}
